SaaS RMS/Models/Entities.System/State.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace SaaS_RMS.Models.Entities.System
{
    public class State
    {
        #region Model Data

        public int StateId { get; set; }

        [Required(ErrorMessage = "Name field is required!!!")]
        public string Name { get; set; }

        #endregion

        #region Enumerables

        public IEnumerable<Lga> Lgas { get; set; }

        //public IEnumerable<Restaurant> Restaurants { get; set; }
        
        #endregion
    }
}

SaaS RMS/Controllers/SystemControllers/StatesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using SaaS_RMS.Data;
using SaaS_RMS.Models.Entities.System;
using SaaS_RMS.Models.Enums;

namespace SaaS_RMS.Controllers.SystemControllers
{
    public class StatesController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IHttpContextAccessor _httpContextAccessor;
        private ISession _session => _httpContextAccessor.HttpContext.Session;

        #region Constructor

        public StatesController(ApplicationDbContext context, IHttpContextAccessor httpContextAccessor)
        {
            _db = context;
            _httpContextAccessor = httpContextAccessor;
        }

        #endregion

        #region States Index

        // GET: States
        [Route("RMS/AllStates")]
        public async Task<IActionResult> Index()
        {
            var rmsadmin = _session.GetInt32("rmsloggedinuserid");

            if (rmsadmin == null)
            {
                return RedirectToAction("Login", "RMS_Admin");
            }

            var _userObject = _session.GetString("rmsloggedinuser");

            if (_userObject == null)
            {
                return RedirectToAction("Login", "RMS_Admin");
            }

            var _user = JsonConvert.DeserializeObject<RMSUser>(_userObject);

            ViewData["name"] = _user.Name;
            ViewData["useremail"] = _user.Email;

            return View(await _db.States.ToListAsync());
        }

        #endregion

        #region States Create

        // GET: States/Create
        public IActionResult Create()
        {
            var state = new State();
            return PartialView("Create", state);
        }

        // POST: States/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("StateId,Name")] State state)
        {
            if (ModelState.IsValid)
            {
                var allStates = _db.States.ToList();
                if (allStates.Any(s => s.Name == state.Name))
                {
                    TempData["state"] = "You cannot add " + state.Name + " state because it already exist!!!";
                    TempData["notificationType"] = NotificationType.Error.ToString();
                    return RedirectToAction("Index", state);
                }

                _db.Add(state);
                await _db.SaveChangesAsync();

                TempData["state"] = "You have successfully added " + state.Name + " as a new State!!!";
                TempData["notificationType"] = NotificationType.Success.ToString();

                return Json(new { success = true });
            }
            return RedirectToAction("Index", state);
        }

        #endregion

        #region States Edit

        // GET: States/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var state = await _db.States.SingleOrDefaultAsync(m => m.StateId == id);
            if (state == null)
            {
                return NotFound();
            }
            return PartialView("Edit", state);
        }

        // POST: States/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("StateId,Name")] State state)
        {
            if (id != state.StateId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _db.Update(state);
                    await _db.SaveChangesAsync();
                    TempData["state"] = "You have successfully modified " + state.Name + " State!!!";
                    TempData["notificationType"] = NotificationType.Success.ToString();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!StateExists(state.StateId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Json(new { success = true });
            }
            return View(state);
        }

        #endregion

        #region States Delete

        // GET: States/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var state = await _db.States
                .SingleOrDefaultAsync(m => m.StateId == id);
            if (state == null)
            {
                return NotFound();
            }

            return PartialView("Delete", state);
        }

        // POST: States/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var state = await _db.States.SingleOrDefaultAsync(m => m.StateId == id);

            if (state != null)
            {
                _db.States.Remove(state);
                await _db.SaveChangesAsync();
                TempData["state"] = "You have successfully deleted " + state.Name + " State!!!";
                TempData["notificationType"] = NotificationType.Success.ToString();
                return Json(new { success = true });
            }
            
            return RedirectToAction("Index", state);
        }

        #endregion

        #region State Exists

        private bool StateExists(int id)
        {
            return _db.States.Any(e => e.StateId == id);
        }

        #endregion

        #region States Details

        // GET: States/Details/5
        //public async Task<IActionResult> Details(int? id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }

        //    var state = await _db.States
        //        .SingleOrDefaultAsync(m => m.StateId == id);
        //    if (state == null)
        //    {
        //        return NotFound();
        //    }

        //    return View(state);
        //}

        #endregion
        
    }
}

SaaS RMS/Views/States/Create.cshtml
@model SaaS_RMS.Models.Entities.System.State

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/AdminLayout/_AdminLayout.cshtml";
}

<div class="row mt">
    <div class="col-md-offset-2 col-md-8">
        <div class="content-panel">
            <div style="padding: 20px;">
                <h2><strong>ADD STATE</strong></h2>
                <section id="unseen">
                    <form asp-action="Create">
                        <div class="form-horizontal">
                            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                            <div class="form-group">
                                <div class="col-md-10">
                                    <input asp-for="Name" class="form-control" placeholder="Name" />
                                    <span asp-validation-for="Name" class="text-danger"></span>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="col-md-offset-2 col-md-10">
                                    <input type="submit" class="btn btn-success" value="Submit" />
                                    <a class="btn btn-warning" asp-action="Index">Cancel</a>
                                </div>
                            </div>
                        </div>
                    </form>
                </section>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SaaS RMS/Views/States/Delete.cshtml
@model SaaS_RMS.Models.Entities.System.State

@{
    ViewData["Title"] = "Delete";
}

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3> <strong> DELETE STATE </strong> </h3>
</div>


<!--MODAL BODY-->
<div class="modal-body">
    <h3 class="text-center"> Are you sure you want to delete @Html.DisplayFor(model => model.Name) State?</h3>
</div>
<form asp-action="Delete">
    <input type="hidden" asp-for="StateId" />

    <!--MODAL FOOTER-->
    <div class="modal-footer">
        <div class="row pull-right">
            <div class="col-md-12">
                <input type="submit" value="Yes" class="btn btn-primary" />
                <a class="btn btn-danger"  data-dismiss="modal">No</a>
            </div>
        </div>
    </div>
</form>

SaaS RMS/Views/States/Edit.cshtml
@model SaaS_RMS.Models.Entities.System.State

@{
    ViewData["Title"] = "Edit";
}

<!--MODAL HEADER-->
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
    <h3> <strong> EDIT STATE </strong> </h3>
</div>

<form asp-action="Edit">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <input type="hidden" asp-for="StateId" />
    <!--MODAL BODY-->
    <div class="modal-body">
        <div class="form-horizontal">
            <div class="row">
                <div class="control-label col-md-2">
                    <label asp-for="Name"></label>
                </div>
                <div class="col-md-10">
                    <input asp-for="Name" class="form-control " />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
            </div>
        </div>
    </div>

    <!--MODAL FOOTER-->
    <div class="modal-footer">
        <div class="row pull-right">
            <div class="col-md-12">
                <input type="submit" value="Save" class="btn btn-primary" />
                <a class="btn btn-danger" data-dismiss="modal">Cancel</a>
            </div>
        </div>
    </div>
</form>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

SaaS RMS/Views/States/Index.cshtml
@model IEnumerable<SaaS_RMS.Models.Entities.System.State>
@using SaaS_RMS.Models.Enums

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/RMS_AdminLayout/_RMS_AdminLayout.cshtml";
    var x = 1;
}


<div style="padding-top:55px;">
    @if (TempData["state"] != null)
    {
        if (TempData["notificationType"].Equals(NotificationType.Success.ToString()))
        {
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                @TempData["state"]
            </div>
        }
        else if (TempData["notificationtype"].Equals(NotificationType.Error.ToString()))
        {
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                @TempData["state"]
            </div>
        }
        else if (TempData["notificationtype"].Equals(NotificationType.Info.ToString()))
        {
            <div class="alert alert-info alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                @TempData["state"]
            </div>
        }

    }
    <div class="page-title">
        <div class="title_left">
            <h3>STATES</h3>
        </div>
    </div>
    <div class="clearfix"></div>
    <div class="row">
        <div class="col-md-12 col-sm-12 col-xs-12">
            <div class="x_panel">
                <div class="x_content">
                    <a asp-area="" asp-controller="States" asp-action="Create" data-modal="" class="btn btn-primary btn pull-right"><i style="color: red;" class="fa fa-plus"></i> ADD</a>
                    <table class="table" id="myTable">
                        <tr>
                            <th>
                                S/N
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                Actions
                            </th>
                        </tr>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @(x++)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    <a class="btn btn-success btn-sm" asp-action="Index" asp-controller="Lgas" asp-route-id="@item.StateId"><i class="fa fa-check"></i> LGA</a>
                                    <a class="btn btn-warning btn-sm" data-modal="" asp-action="Edit" asp-route-id="@item.StateId"><i class="fa fa-pencil-square-o "></i> Edit</a>
                                    <a class="btn btn-danger btn-sm" data-modal="" asp-action="Delete" asp-route-id="@item.StateId"><i class="fa fa-trash-o "></i> Delete</a>
                                </td>
                            </tr>
                        }
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<script src="~/Admin/vendors/jquery/dist/jquery.min.js"></script>
<script src="~/Modal/Modal.js"></script>

<!-- modal placeholder-->
<div id='myModal' class='modal fade in'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div id='myModalContent'>
            </div>
        </div>
    </div>
</div>