SaaS RMS/Controllers/RestaurantsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SaaS_RMS.Data;
using SaaS_RMS.Models.Entities.System;
using SaaS_RMS.Models.Enums;

namespace SaaS_RMS.Controllers
{
    public class RestaurantsController : Controller
    {
        private readonly ApplicationDbContext _db;

        #region Constructor

        public RestaurantsController(ApplicationDbContext context)
        {
            _db = context;
        }

        #endregion

        #region Restaurant Index

        public async Task<IActionResult> Index()
        {
            return View(await _db.Restaurants.ToListAsync());
        }

        #endregion

        #region Restaurant Register

        public async Task<IActionResult> Register(Restaurant restaurant)
        {
            if (ModelState.IsValid)
            {
                if (await _db.Restaurants.AnyAsync(r => r.Name == restaurant.Name))
                {
                    ModelState.AddModelError("", "Restaurant name already exists");
                }

                if(await _db.Restaurants.AnyAsync(r => r.ContactEmail == restaurant.ContactEmail))
                {
                    ModelState.AddModelError("", "Contact Email already exists");
                }

                else
                {
                    _db.Restaurants.Add(restaurant);
                    _db.SaveChanges();

                    TempData["Success"] = restaurant.Name + " have successfully joined the Odarms community";
                    TempData["notificationType"] = NotificationType.Success.ToString();
                    return Json(new { success = true });
                }
                
            }
            return View();
        }

        #endregion


    }
}

SaaS RMS/Views/Shared/RMS_AdminLayout/_RMS_AdminLayout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <environment names="Development">
        <!-- Bootstrap -->
        <link href="~/Admin/vendors/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- Font Awesome -->
        <link href="~/Admin/vendors/font-awesome/css/font-awesome.min.css" rel="stylesheet">
        <!-- NProgress -->
        <link href="~/Admin/vendors/nprogress/nprogress.css" rel="stylesheet">
        <!-- bootstrap-daterangepicker -->
        <script src="~/Admin/vendors/moment/min/moment.min.js"></script>
        <link href="~/Admin/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
        <!-- Ion.RangeSlider -->
        <link href="~/Admin/vendors/normalize-css/normalize.css" rel="stylesheet">
        <link href="~/Admin/vendors/ion.rangeSlider/css/ion.rangeSlider.css" rel="stylesheet">
        <link href="~/Admin/vendors/ion.rangeSlider/css/ion.rangeSlider.skinFlat.css" rel="stylesheet">
        <!-- iCheck -->
        <link href="~/Admin/vendors/iCheck/skins/flat/green.css" rel="stylesheet">
        <!-- DataTables -->
        <link href="~/DataTables/jquery.dataTables.css" rel="stylesheet" />
        <link href="~/DataTables/table-responsive.css" rel="stylesheet" />
        <!-- bootstrap-progressbar -->
        <link href="~/Admin/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css" rel="stylesheet">
        <!-- JQVMap -->
        <link href="~/Admin/vendors/jqvmap/dist/jqvmap.min.css" rel="stylesheet" />
        <!-- bootstrap-daterangepicker -->
        <link href="~/Admin/vendors/bootstrap-daterangepicker/daterangepicker.css" rel="stylesheet">
        <!-- Custom Theme Style -->
        <link href="~/Admin/build/css/custom.min.css" rel="stylesheet">

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body class="nav-md">
    <div class="container body">
        <div class="main_container">
            <div class="col-md-3 left_col">
                <div class="left_col scroll-view">
                    <div class="navbar nav_title" style="border: 0;">
                        <a href="index.html" class="site_title"><i class="fa fa-paw"></i> <span>Odarms</span></a>
                    </div>
                    <div class="clearfix"></div>
                    <!-- menu profile quick info -->
                    <div class="profile clearfix">
                        <div class="profile_pic">
                            <img src="images/img.jpg" alt="..." class="img-circle profile_img">
                        </div>
                        <div class="profile_info">
                            <span>Welcome,</span>
                            <h2>@ViewData["name"]</h2>
                        </div>
                    </div>
                    <!-- /menu profile quick info -->
                    <br />
                    <!-- sidebar menu -->
                    @Html.Partial("~/Views/Shared/RMS_AdminLayout/_RMS_AdminLayoutSidebar.cshtml")
                    <!-- /sidebar menu -->


                </div>
            </div>
            <!-- top navigation -->
            @Html.Partial("~/Views/Shared/RMS_AdminLayout/_RMS_AdminLayoutHeader.cshtml")
            <!-- /top navigation -->
            <!-- page content -->
            <div class="right_col" role="main">
                @RenderBody()
            </div>
            <!-- /page content -->
            <!-- footer content -->
            <footer>
                <div class="pull-right">
                    <h5> <strong> Odarms</strong> </h5>
                </div>
                <div class="clearfix"></div>
            </footer>
            <!-- /footer content -->
        </div>
    </div>

    <environment names="Development">
        <!-- jQuery -->
        <script src="~/Admin/vendors/jquery/dist/jquery.min.js"></script>
        <!-- DataTables -->
        <script src="~/DataTables/jquery.dataTables.js"></script>
        <!-- Bootstrap -->
        <script src="~/Admin/vendors/bootstrap/dist/js/bootstrap.min.js"></script>
        <!-- FastClick -->
        <script src="~/Admin/vendors/fastclick/lib/fastclick.js"></script>
        <!-- NProgress -->
        <script src="~/Admin/vendors/nprogress/nprogress.js"></script>
        <!-- jQuery Smart Wizard -->
        <script src="~/Admin/vendors/jQuery-Smart-Wizard/js/jquery.smartWizard.js"></script>
        <!-- Chart.js -->
        <script src="~/Admin/vendors/Chart.js/dist/Chart.min.js"></script>
        <!-- gauge.js -->
        <script src="~/Admin/vendors/gauge.js/dist/gauge.min.js"></script>
        <!-- bootstrap-progressbar -->
        <script src="~/Admin/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js"></script>
        <!-- iCheck -->
        <script src="~/Admin/vendors/iCheck/icheck.min.js"></script>
        <!-- Skycons -->
        <script src="~/Admin/vendors/skycons/skycons.js"></script>
        <!-- Flot -->
        <script src="~/Admin/vendors/Flot/jquery.flot.js"></script>
        <script src="~/Admin/vendors/Flot/jquery.flot.pie.js"></script>
        <script src="~/Admin/vendors/Flot/jquery.flot.time.js"></script>
        <script src="~/Admin/vendors/Flot/jquery.flot.stack.js"></script>
        <script src="~/Admin/vendors/Flot/jquery.flot.resize.js"></script>
        <!-- Flot plugins -->
        <script src="~/Admin/vendors/flot.orderbars/js/jquery.flot.orderBars.js"></script>
        <script src="~/Admin/vendors/flot-spline/js/jquery.flot.spline.min.js"></script>
        <script src="~/Admin/vendors/flot.curvedlines/curvedLines.js"></script>
        <!-- DateJS -->
        <script src="~/Admin/vendors/DateJS/build/date.js"></script>
        <!-- JQVMap -->
        <script src="~/Admin/vendors/jqvmap/dist/jquery.vmap.js"></script>
        <script src="~/Admin/vendors/jqvmap/dist/maps/jquery.vmap.world.js"></script>
        <script src="~/Admin/vendors/jqvmap/examples/js/jquery.vmap.sampledata.js"></script>
        <!-- bootstrap-daterangepicker -->
        <script src="~/Admin/vendors/moment/min/moment.min.js"></script>
        <script src="~/Admin/vendors/bootstrap-daterangepicker/daterangepicker.js"></script>
        <!-- Custom Theme Scripts -->
        <script src="~/Admin/build/js/custom.min.js"></script>

    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

SaaS RMS/Views/Shared/RMS_AdminLayout/_RMS_AdminLayoutHeader.cshtml
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>
            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="images/img.jpg" alt="">@ViewData["name"]
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a href="javascript:;"> Profile</a></li>
                        <li><a asp-action="Logout" asp-controller="RMS_Admin"><i class="fa fa-sign-out pull-right"></i> Log Out</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </div>
</div>

SaaS RMS/Views/Shared/RMS_AdminLayout/_RMS_AdminLayoutSidebar.cshtml
<div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
    <div class="menu_section">
        <h3>General</h3>
        <ul class="nav side-menu">
            <li>
                <a asp-controller="Restaurants" asp-action="Index"><i class="fa fa-home"></i> Restaurants</a>
            </li>
            <li>
                <a asp-controller="CompanyVendors" asp-action="Index"><i class="fa fa-archive"></i> Vendors</a>
            </li>
            <li>
                <a asp-controller="Customers" asp-action="Index"><i class="fa fa-archive"></i> Customers</a>
            </li>
            <li>
                <a asp-controller="Packages" asp-action="Index"><i class="fa fa-archive"></i> Packages</a>
            </li>
            <li>
                <a asp-controller="States" asp-action="Index"><i class="fa fa-archive"></i> States</a>
            </li>
            <li>
                <a asp-controller="LandingInfo" asp-action="Index"><i class="fa fa-archive"></i> Landing Infomation</a>
            </li>
        </ul>
    </div>
    
</div>

<!-- /menu footer buttons -->
<div class="sidebar-footer hidden-small">
    <a data-toggle="tooltip" data-placement="top" title="Settings">
        <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="FullScreen">
        <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Lock">
        <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
    </a>
    <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
        <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
    </a>
</div>
<!-- /menu footer buttons -->